# Generated by Django 2.1.4 on 2019-01-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MSc', 'MSc'), ('BCA', 'BCA'), ('BSC(IT)', 'BSC(IT)'), ('BSC(CS)', 'BSC(CS)'), ('VISCOM', 'VISCOM'), ('BBA', 'BBA'), ('SSA', 'SSA'), ('BA', 'BA'), ('MA', 'MA'), ('Bcom(CA)', 'Bcom(CA)')], default='MCA', max_length=7),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='destination',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('HOD', 'HOD')], default='STUDENT', max_length=7),
        ),
    ]
