# Generated by Django 2.1.4 on 2019-01-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobfair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('eventdate', models.CharField(max_length=100)),
                ('seminarperson', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('deptment', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('eligibility', models.CharField(max_length=100)),
                ('cgb', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
    ]
