# Generated by Django 2.1.4 on 2019-01-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfair',
            name='deptment',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MSc', 'MSc'), ('BCA', 'BCA'), ('BSC(IT)', 'BSC(IT)'), ('BSC(CS)', 'BSC(CS)'), ('VISCOM', 'VISCOM'), ('BBA', 'BBA'), ('SSA', 'SSA'), ('BA', 'BA'), ('MA', 'MA'), ('Bcom(CA)', 'Bcom(CA)')], default='MCA', max_length=7),
        ),
    ]
